'\" t
.\"     Title: snapperd
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2012-10-15
.\"    Manual: Filesystem Snapshot Management
.\"    Source: 0.8.3
.\"  Language: English
.\"
.TH "SNAPPERD" "8" "2012\-10\-15" "0\&.8\&.3" "Filesystem Snapshot Management"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
snapperd \- DBus daemon for snapper
.SH "SYNOPSIS"
.HP \w'\fBsnapperd\fR\ 'u
\fBsnapperd\fR
.SH "DESCRIPTION"
.PP
Snapperd is a DBus daemon for snapper and not for direct use by the user\&.
.SH "HOMEPAGE"
.PP
\m[blue]\fBhttp://snapper\&.io/\fR\m[]
.SH "AUTHORS"
.PP
Arvin Schnell
<aschnell@suse\&.com>
.SH "SEE ALSO"
.PP
\fBsnapper\fR(8),
\fBdbus-daemon\fR(1)
