'\" t
.\"     Title: snapper-zypp-plugin
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2013-11-22
.\"    Manual: Filesystem Snapshot Management
.\"    Source: 0.8.3
.\"  Language: English
.\"
.TH "SNAPPER\-ZYPP\-PLUGI" "8" "2013\-11\-22" "0\&.8\&.3" "Filesystem Snapshot Management"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
snapper-zypp-plugin \- Snapper plugin for libzypp
.SH "DESCRIPTION"
.PP
With the snapper\-zypp\-plugin, snapper can create snapshots whenever libzypp, and thus e\&.g\&. zypper and YaST, installs, updates or removes packages\&.
.SH "FILES"
.PP
/etc/snapper/zypp\-plugin\&.conf
.RS 4
Configuration file\&. New in version 0\&.1\&.8\&.
.RE
.SH "HOMEPAGE"
.PP
\m[blue]\fBhttp://snapper\&.io/\fR\m[]
.SH "AUTHORS"
.PP
Arvin Schnell
<aschnell@suse\&.com>
.SH "SEE ALSO"
.PP
\fBsnapper-zypp-plugin.conf\fR(5),
\fBsnapper\fR(8),
\fBzypper\fR(8),
\fBYaST\fR(8)
