'\" t
.\"     Title: snapper-zypp-plugin.conf
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2013-11-22
.\"    Manual: Filesystem Snapshot Management
.\"    Source: 0.8.3
.\"  Language: English
.\"
.TH "SNAPPER\-ZYPP\-PLUGI" "5" "2013\-11\-22" "0\&.8\&.3" "Filesystem Snapshot Management"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
snapper-zypp-plugin.conf \- Configuration file for snapper\-zypp\-plugin
.SH "DESCRIPTION"
.PP
The file
/etc/snapper/zypp\-plugin\&.conf
contains the configuation for snapper\-zypp\-plugin\&.
.PP
The file uses XML syntax\&. For the XML structure have a look at the provided default config\&.
.SH "HOMEPAGE"
.PP
\m[blue]\fBhttp://snapper\&.io/\fR\m[]
.SH "AUTHORS"
.PP
Arvin Schnell
<aschnell@suse\&.com>
.SH "SEE ALSO"
.PP
\fBsnapper-zypp-plugin\fR(8)
